baseURL = "/"
languageCode = "en-us"
title = "BIC at BCX'19"
themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[[menu.main]]
    name = "Examples"
    url = "/examples/"
    weight = 3

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'documentation'
  homepage_intro = 'Pivotal presents BIC at BCX`19 - read the docs and ask the team'
  homepage_image = '/images/pivotal.png'

  [params.homepage_meta_tags]
    meta_description = "Pivotal presents BIC at BCX`19 - read the docs and ask the team"
    meta_og_title = "Pivotal presents BIC at BCX`19"
    meta_og_type = "website"
    meta_og_url = "https://www.bic4bcx.de"
    meta_og_image = "/images/favicon.ico"
    meta_og_description = "Pivotal presents BIC at BCX`19 - read the docs and ask the team"
    meta_twitter_card = "summary"
    meta_twitter_site = "@cjuette"
    meta_twitter_creator = "@cjuette"

  [params.logo]
      mobile = "/images/pivotal.png"
      standard  = "/images/pivotal.png"
